[platformio]
default_envs = uno
src_dir = apps/reference_firmware/src

[env:uno]
platform = atmelavr
board = uno
framework = arduino
upload_port = auto
extra_scripts = pre:tools/git_version.py
build_flags =
	-I lib/IOFusion/include
	-I apps/reference_firmware/include

[env:native]
platform = native
test_build_src = yes
lib_compat_mode = off
build_src_filter =
	+<firmware_cli.cpp>
	-<main.cpp>
build_flags =
	-I lib/IOFusion/include
	-I apps/reference_firmware/include
	-I test/mocks
	-fno-exceptions
	-fprofile-arcs
	-ftest-coverage
	--coverage
	-lgcov
	-O0
	-g

